name: hsp
channels:
  - anaconda
  - pytorch
  - conda-forge
dependencies:
  - Pytorch=1.4.0
  - Torchvision=0.5.0
  - numpy=1.18.1
  - scikit-learn=0.22.1
  - matplotlib=3.1.1
  - Pandas=0.25.3
  - Nibabel=3.0.0
  - Tqdm=4.42.1
  - enlighten=1.8.0